var FilterConstants = {
  SEARCHMAPMOVED: "SEARCHMAPMOVED",
  UPDATECHECKIN: "UPDATECHECKIN",
  UPDATECHECKOUT: "UPDATECHECKOUT",
  UPDATEGUESTS: "UPDATEGUESTS",
  UPDATEDATES: "UPDATEDATES",
  UPDATEPRICERANGE: "UPDATEPRICERANGE",
  TOGGLE_ROOM_TYPE: "TOGGLE_ROOM_TYPE",
  RESETDATES: "RESETDATES"
}

module.exports = FilterConstants;
